"""
Program to test the riverProblem implementation.

BOILERPLATE, DO NOT EDIT THIS FILE.  If you wish to test your implementation
differently during development, add a main() function to the riverProblem
module itself.
"""
from riverProblem import River_problem
from searchGeneric import AStarSearcher

def smoke_test():
    """
    Trivial test to check that the solution will even run.
    Feel free to add additional tests.
    """
    print("testing...")
    prob = River_problem()
    assert prob.start_node() is not None
    assert not prob.is_goal(prob.start_node())
    assert prob.heuristic(prob.start_node()) >= 0

    ns = prob.neighbors(prob.start_node())
    assert len(ns) > 0
    for n in ns:
        assert n.from_node == prob.start_node()
    print("tests ok")
    
def main():
    smoke_test()
    prob = River_problem()
    s = AStarSearcher(prob)
    path = s.search()
    if path:
        print("Path found (cost=%s)\n%s" % (path.cost, path))
        return path

if __name__ == '__main__':
    main()
